# Basic config
baseURL = "https://blog.anishgoyal.com"
theme = "hugo-simple"
languageCode = "en"
title = "Anish Goyal"
copyright = "Â© 2024 Anish Goyal"

# Generate a nice robots.txt for SEO
enableRobotsTXT = true

# https://github.com/gohugoio/hugo/issues/12152
capitalizeListTitles = false

# Generate "Bearblog"-like URLs !only!, see https://bearblog.dev/.
disableKinds = ["taxonomy"]
# ignoreErrors = ["error-disable-taxonomy"]
[taxonomies]
tag = "tags"

[permalinks]
blog = "/:slug/"
tags = "/blog/:slug"

[blackfriday]
smartypants = true
fractions = true
smartDashes = true
plainIDAnchors = true

[markup.goldmark.renderer]
unsafe = true

[markup.tableOfContents]
startLevel = 2
endLevel = 3

[markup.highlight]
lineNos = true
lineNumbersInTable = false
noClasses = true
style = "catppuccin-mocha"

[params]
title = "Anish Goyal's Tech Blog"
description = "Welcome to my blog!"
dateFormat = "01-02-2006"
hideMadeWithLine = true
hideRSSLink = true

[params.author]
name = "Anish Goyal"
email = "anishgoyal1108@gmail.com"

[[menu.main]]
name = "ğŸ  Home"
pageRef = "/"
weight = 10

[[menu.main]]
name = "ğŸ“ƒ Blog"
pageRef = "/blog"
weight = 20

[[menu.main]]
name = "ğŸ¥· Writeups"
pageRef = "/writeups"
weight = 30

[[menu.main]]
name = "ğŸ·ï¸ Tags"
pageRef = "/tags"
weight = 40

[[menu.main]]
name = "ğŸ“° RSS"
url = "/index.xml"
weight = 50

[outputs]
# Generate RSS for home only.
section = ["html"]
taxonomy = ["html"]
term = ["html"]
